server:
  port: 2022

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: fsp_tx_group #自定义事务组名称与seata-server中的对应
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.46.247:3306/seata_account?useSSL=false&characterEncoding=utf8
    username: root
    password: abc123!

feign:
  hystrix:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
