server:
  port: 8003

spring:
  application:
    name: cloud-payment-hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7000/eureka
  instance:
    instance-id: payment8003
    prefer-ip-address: true