server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/timeout/**
            - After=2020-06-18T11:26:01.815+08:00[Asia/Shanghai]

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
#            - After=2020-06-18T11:26:01.815+08:00[Asia/Shanghai] #在这个日期之后才能访问
#            - Cookie=username,ch
#            - Header=X-Request-Id,\d+
#          Filter:


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7000/eureka