server:
  port: 3355

spring:
  application:
    name: cloud-client-3355
  cloud:
    config:
      label: master #分支名称
      name: config
      profile: dev
      uri: http://localhost:3000



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7000/eureka
